bug: { color: 'd73a4a', description: 'Something is not working' }
chore: { color: 'cccccc', description: 'Maintenance or chores' }
documentation: { color: '0075ca', description: 'Improvements or additions to documentation' }
enhancement: { color: 'a2eeef', description: 'New feature or request' }
governance: { color: '5319e7', description: 'Governance & process changes' }
tech-debt: { color: 'b60205', description: 'Refactors or debt paydown' }
tests: { color: '0e8a16', description: 'Testing additions or improvements' }
