name: push-guard

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'github-actions[bot]'
    steps:
      - name: Prevent direct pushes to protected branches
        run: |
          echo "Direct pushes to 'main' or 'develop' are disallowed. Use a PR via develop -> main." >&2
          exit 1
